### ISSUE TITLE
Strange Floating Rectangles in Atmosphere

### ISSUE THREAD

**Issue by SlainteMaith** [KerbalFrench/KSRSS#2]
**_Title:_** Strange rectangles appear in earth's atmosphere in 2.5x resize.*

**_Steps to reproduce:_**
1. Install fresh Kerbal 1.7.1
2. Install mods listed in Files.txt (All mods as indicated by KSRSS install + 2.5x Resize, apart from MechJeb and Cormorant Aeronology Shuttle + 2.5x patch for shuttle)
3. Run Program.
4. Launch Vehicle to 151km x 41km (I believe the Pe doesn't matter so long as it's LEOish)

**_Observed result:_**
Rectangles appear in earth's sky below.

**_Expected Result:_**
No rectangles should be floating in earth's atmosphere.

**_Attachments and Notes:_**

*Might be scatterer or eve.  Tester is aware the bug might not be related to KSRSS.

[Files.txt](https://github.com/KerbalFrench/KSRSS/files/3384193/Files.txt)

[Logs.zip](https://github.com/KerbalFrench/KSRSS/files/3384215/Logs.zip)

![KSP Rectangles](https://user-images.githubusercontent.com/30164077/61088870-618f0500-a407-11e9-8086-144e185e29f4.jpg)

**Comment by tony48** [comment]
Fixed by e4cb6d4

**Comment by SlainteMaith** [comment]
Confirm: appears fixed when replicating steps to reproduce.
